services:
  app:
    container_name: nextjs-admin
    build:
      target: deps
    command: npm run dev
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - express-core-network

networks:
  express-core-network:
    external: true
